### ISSUE TITLE
查询报错

### ISSUE THREAD

**Issue by smarteng** [rosbit/go-search#1]
创建文档和查询报错，都是跟 lru相关的，难道是我设置的不对？
{
    "listen-host": "",
    "listen-port": 7080,
    "worker-num": 5,
    "timeout": 0,
    "root-dir": "./schema-home",
	"lru-minutes": 10
}
$ go version
go version go1.14 linux/amd64

go search 是最新版本

**Comment by smarteng** [comment]
[negroni] PANIC: runtime error: invalid memory address or nil pointer dereference
goroutine 51 [running]:
github.com/urfave/negroni.(*Recovery).ServeHTTP.func1(0x7fbb82377138, 0xc0000100d0, 0xc0004da050, 0xc000174300)
	/pkg/mod/github.com/urfave/negroni@v1.0.0/recovery.go:159 +0x147
panic(0xba9560, 0x126dc20)
	/usr/local/go/src/runtime/panic.go:973 +0x3ce
github.com/hashicorp/golang-lru.(*Cache).Add(0x0, 0xb79b80, 0xc0004c0070, 0xc45940, 0xc0004c4000, 0xc000028600)
	/pkg/mod/github.com/hashicorp/golang-lru@v0.5.3/lru.go:42 +0x2b
go-search/indexer.lruAdd(0xc000026366, 0x4)
	/go-search/indexer/lru.go:46 +0x129
go-search/indexer.initIndexer(0xc000026366, 0x4, 0x0, 0x0, 0x0)
	/go-search/indexer/index-initer.go:62 +0x6b5
go-search/indexer.IndexDoc(0xc000026366, 0x4, 0xc0001845a0, 0x0, 0x0, 0x0, 0x0)
	/go-search/indexer/doc-indexer.go:28 +0x82
go-search/rest.updateDoc(0xc000184540, 0xc90c50, 0xc6b70a, 0x12)
	/go-search/rest/index.go:44 +0x202
go-search/rest.IndexDoc(0xc000184540)
	/go-search/rest/index.go:20 +0x4c
github.com/rosbit/http-helper.unwrap.func1(0x7fbb82377138, 0xc0000100d0, 0xc000174300)
	/pkg/mod/github.com/rosbit/http-helper@v0.0.3/context-mux.go:12 +0x60
net/http.HandlerFunc.ServeHTTP(0xc0004c01c0, 0x7fbb82377138, 0xc0000100d0, 0xc000174300)
	/usr/local/go/src/net/http/server.go:2012 +0x44
github.com/gernest/alien.(*route).ServeHTTP(0xc0004bc900, 0x7fbb82377138, 0xc0000100d0, 0xc000174300)
	/pkg/mod/github.com/gernest/alien@v0.1.0/alien.go:169 +0x12e
github.com/gernest/alien.(*Mux).ServeHTTP(0xc0004c6100, 0x7fbb82377138, 0xc0000100d0, 0xc000174300)
	/pkg/mod/github.com/gernest/alien@v0.1.0/alien.go:470 +0x298
github.com/urfave/negroni.Wrap.func1(0x7fbb82377138, 0xc0000100d0, 0xc000174300, 0xc00000e100)
	/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:46 +0x59
github.com/urfave/negroni.HandlerFunc.ServeHTTP(0xc0004c4160, 0x7fbb82377138, 0xc0000100d0, 0xc000174300, 0xc00000e100)
	/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:29 +0x4e
github.com/urfave/negroni.middleware.ServeHTTP(0xd2ae00, 0xc0004c4160, 0xc0004c41c0, 0x7fbb82377138, 0xc0000100d0, 0xc000174300)
	/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:38 +0xbd
github.com/urfave/negroni.(*Logger).ServeHTTP(0xc0004bc2d0, 0x7fbb82377138, 0xc0000100d0, 0xc000174300, 0xc00000e0e0)
	/pkg/mod/github.com/urfave/negroni@v1.0.0/logger.go:62 +0x90
github.com/urfave/negroni.middleware.ServeHTTP(0xd2a0e0, 0xc0004bc2d0, 0xc0004c41a0, 0x7fbb82377138, 0xc0000100d0, 0xc000174300)
	/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:38 +0xbd
github.com/urfave/negroni.(*Recovery).ServeHTTP(0xc0004da050, 0x7fbb82377138, 0xc0000100d0, 0xc000174300, 0xc00000e0c0)
	/pkg/mod/github.com/urfave/negroni@v1.0.0/recovery.go:193 +0xc1
github.com/urfave/negroni.middleware.ServeHTTP(0xd2a120, 0xc0004da050, 0xc0004c4180, 0x7fbb82377138, 0xc0000100d0, 0xc000174300)
	/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:38 +0xbd
github.com/urfave/negroni.(*Negroni).ServeHTTP(0xc0004bc2a0, 0xd332e0, 0xc0001642a0, 0xc000174300)
	/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:96 +0xea
github.com/rosbit/http-helper.(*HttpHelper).ServeHTTP(0xc0004c0170, 0xd332e0, 0xc0001642a0, 0xc000174300)
	/pkg/mod/github.com/rosbit/http-helper@v0.0.3/helper.go:29 +0x53
net/http.serverHandler.ServeHTTP(0xc0004e0000, 0xd332e0, 0xc0001642a0, 0xc000174300)
	/usr/local/go/src/net/http/server.go:2807 +0x20f
net/http.(*conn).serve(0xc000128320, 0xd34ba0, 0xc000038080)
	/usr/local/go/src/net/http/server.go:1895 +0x1716
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2933 +0x931

**Comment by smarteng** [comment]
![image](https://user-images.githubusercontent.com/663786/121110411-d2cbd280-c83f-11eb-9bc7-784fa148841a.png)
是在这句报错了

**Comment by rosbit** [comment]
正常操作流程：

**Comment by rosbit** [comment]
正常操作流程
  - 启动服务
  - 创建索引库
  - 添加数据
  - 搜索
 
这些步骤是否都有正常执行？

**Comment by smarteng** [comment]
> 正常操作流程
> 
> * 启动服务
> * 创建索引库
> * 添加数据
> * 搜索
> 
> 这些步骤是否都有正常执行？
创建索引库 正常，
添加数据 报错 ，把上面报错的语句注释掉，添加成功，
搜索 报错

**Comment by rosbit** [comment]
"lru-minutes": 0

**Comment by rosbit** [comment]
> > 正常操作流程
> > 
> > * 启动服务
> > * 创建索引库
> > * 添加数据
> > * 搜索
> > 
> > 这些步骤是否都有正常执行？
> > 创建索引库 正常，
> > 添加数据 报错 ，把上面报错的语句注释掉，添加成功，
> > 搜索 报错

你把LRU时间设为0吧：` "lru-minutes": 10`

**Comment by rosbit** [comment]
> > 正常操作流程
> > 
> > * 启动服务
> > * 创建索引库
> > * 添加数据
> > * 搜索
> > 
> > 这些步骤是否都有正常执行？
> > 创建索引库 正常，
> > 添加数据 报错 ，把上面报错的语句注释掉，添加成功，
> > 搜索 报错

你把LRU时间设为0吧: `"lru-minutes": 0`

**Comment by smarteng** [comment]
> > > 正常操作流程
> > > 
> > > * 启动服务
> > > * 创建索引库
> > > * 添加数据
> > > * 搜索
> > > 
> > > 这些步骤是否都有正常执行？
> > > 创建索引库 正常，
> > > 添加数据 报错 ，把上面报错的语句注释掉，添加成功，
> > > 搜索 报错
> 
> 你把LRU时间设为0吧: `"lru-minutes": 0`

`"lru-minutes": 0` 就正常了，感谢，
这是由于什么情况造成的呢 ？

**Comment by rosbit** [comment]
> > > > 正常操作流程
> > > > 
> > > > * 启动服务
> > > > * 创建索引库
> > > > * 添加数据
> > > > * 搜索
> > > > 
> > > > 这些步骤是否都有正常执行？
> > > > 创建索引库 正常，
> > > > 添加数据 报错 ，把上面报错的语句注释掉，添加成功，
> > > > 搜索 报错
> > 
> > 
> > 你把LRU时间设为0吧: `"lru-minutes": 0`
> 
> `"lru-minutes": 0` 就正常了，感谢，
> 这是由于什么情况造成的呢 ？

这个LRU针对的是这样的场景：
 - 索引数据是临时性的
 - 索引数据提供完服务后不想驻留内存
 - 系统通过LRU主动释放索引

**Comment by smarteng** [comment]
> > > > > 正常操作流程
> > > > > 
> > > > > * 启动服务
> > > > > * 创建索引库
> > > > > * 添加数据
> > > > > * 搜索
> > > > > 
> > > > > 这些步骤是否都有正常执行？
> > > > > 创建索引库 正常，
> > > > > 添加数据 报错 ，把上面报错的语句注释掉，添加成功，
> > > > > 搜索 报错
> > > 
> > > 
> > > 你把LRU时间设为0吧: `"lru-minutes": 0`
> > 
> > 
> > `"lru-minutes": 0` 就正常了，感谢，
> > 这是由于什么情况造成的呢 ？
> 
> 这个LRU针对的是这样的场景：
> 
> * 索引数据是临时性的
> * 索引数据提供完服务后不想驻留内存
> * 系统通过LRU主动释放索引

谢谢

**Comment by smarteng** [comment]
问题解决
